# Generated by Django 4.1.6 on 2024-05-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='expires_in',
            field=models.DateField(verbose_name='expires in'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
    ]
